### PR TITLE
Parallelization

### PR DESCRIPTION
**Pull request by c0sc0**
Simple joblib wrapper for anomaly detection, cut runtime to 100 seconds in my case

Also filtering ETFs per #14

### CODE REVIEW

**Comment by StevenAdema** [comment]
Wow, that's a huge improvement on runt time 👍

**Comment by Stjernex24** [comment]
Hi could you help me install on mobile? Or is this only for desktop? I have
pydroid 3 installed on mobile where do I go from here? I don't understand
how to input code into pydroid.

**Comment by luisott** [comment]
FYI this got reverted because it broke something maybe? Can we get the code that removes the ETFs in its own PR so that we could merge it soon? It really helps with the speed. We could look into what was breaking for the threading as a separate issue

**Comment by c0sc0** [comment]
> FYI this got reverted because it broke something maybe? Can we get the code that removes the ETFs in its own PR so that we could merge it soon? It really helps with the speed. We could look into what was breaking for the threading as a separate issue

I think the issue was joblib picking whatever backend it wants (the threading/multiprocessing backend breaks yfinance, but the loki backend 'processes' works fine, there's just no synchronization between the processes. I have that all fixed now (at least on my machine!) Also seeing people running this on Android, have no way of testing that unfortunately

#14 has been already merged btw

**Comment by luisott** [comment]
awesome, the parallel processes worked for me always

**Pull request merged**
