### PR TITLE
Adding send email functionality

### PR DESCRIPTION
**Pull request by nicbuilds1**
This merge would add send email functionality to the script. Note that gmail configuration would need to be supplied. Running this script on a timer such as with Linux's cron will allow automatic emails to be sent.

### CODE REVIEW

**Comment by luisott** [comment]
Awesome

**Comment by luisott** [comment]
Should these configurations for the email live outside the script in its own file and have that file added to the .gitignore so that people accidentally don't commit sensitive information?

**Comment by Connor9994** [comment]
> Should these configurations for the email live outside the script in its own file and have that file added to the .gitignore so that people accidentally don't commit sensitive information?

Exactly what came to mind when I considered the addition myself haha

**Comment by luisott** [comment]
Code looks great! Testing it now

**Comment by nward17** [comment]
> there you go

Lol, only took like 10 tries.

**Comment by luisott** [comment]
Tried it but I didn't get the email and the script didn't return any matches either, it just hanged there after 100% without exiting. Can we add some error output if something goes wrong? And still print the ticker matches even when email doesn't workout?

**Comment by cogsworth37** [comment]
IMO this function should be pulled into another class/file. I think that the market_scanner.py is getting very very busy and a good rule of thumb for coding is to ensure that classes/functions do one thing.

**Comment by luisott** [comment]
> IMO this function should be pulled into another class/file. I think that the market_scanner.py is getting very very busy and a good rule of thumb for coding is to ensure that classes/functions do one thing.

Agree. Also having it in a separate script could also allow us to do fancy things like loop forever and only send an email if there's a new ticker, without affecting the main functionality

**Pull request closed without merging**
