### PR TITLE
Merging some more PRs, this time auto-mergable

### PR DESCRIPTION
**Pull request by c0sc0**
see #32 #33 #34 #40 

shout out to @alexshirley for the pandas refactor!

### CODE REVIEW

**Comment by c0sc0** [comment]
Confirmed the off-by-one bug (fixed it already), just ran the fixed script and it picked up $ADT, $DPHC, $DTSS, $FORD, and $HIHO for today

@SamPom100

**Comment by c0sc0** [comment]
Now tracking number of deviations from mean. The dynamic site handles multi-variate sorting so I cranked down the STD limit and it's working great!

(I commented out the customPrints because they were starting to slow down the script with a bunch of hits, left it there for testing purposes but everything's printed out at the end)

also started a todo list in the readme

**Comment by c0sc0** [comment]
Can now rescan directly from the dynamic web interface!

Will try rescanning on a timer and make the dynamic page auto refresh so I can toss this onto a Hetzner box or a DO droplet or something. In the meantime, this is LAN-only. Should really add a server-side mutex on reloading but whatever (don't want to give users that control anyways hahaha)

@SamPom100 

[Reloading](https://i.imgur.com/IY6Id64.png)

[Reloaded](https://i.imgur.com/ShxBWBd.png)

**Comment by c0sc0** [comment]
Also, the dynamic site (mostly the input validation) is hilariously broken on mobile (in portrait). Not really worried about it tbh. Just be careful ;)

edit: nevermind, flexbox fixes everything (except for the input). Ticker in table is still cut off but landscape looks good

**Comment by SamPom100** [comment]
new website looks good, but most people have been browsing from mobile so I'd like it to work in portrait and scale. Fixed the T-1 bug. Also, most of the feedback I got on reddit asked for easy variables to adjust, thats why I declare them above  instead of as arguments.

**Comment by c0sc0** [comment]
I'm working on fixing portrait now (damn DataTables)

The reason I did it with member variables is so I can import the scanner module in a different script and change things up like i do in flask_server when rescanning

`stonk_search = mainObj(_month_cuttoff=month_cut,_day_cuttoff=day_cut,_std_cuttoff=std_cut)`

Will add command line arguments (eg, python market_scanner.py 6 3 9) and if they aren't provided, prompt the user to enter their cutoffs (and suggest defaults). Sounds like a good compromise!

**Comment by elizabethshirley** [comment]
Tyyyyler, wrap up this PR!

**Comment by c0sc0** [comment]
hahaha sorry I just kept on adding shit

**Comment by elizabethshirley** [comment]
Yeah, but no one else can effectively add or clean up while the PR is open

**Comment by Stjernex24** [comment]
> Also, the dynamic site (mostly the input validation) is hilariously broken on mobile (in portrait). Not really worried about it tbh. Just be careful ;)
> 
> edit: nevermind, flexbox fixes everything (except for the input). Ticker in table is still cut off but landscape looks good

Only works for desktop atm got it. Noticed major delay for ticker ALIM around 3pm or so on mobile. What could I do to get the alert asap

**Comment by c0sc0** [comment]
am a GitHub scrub ;) will fix my shit when I get home

**Comment by c0sc0** [comment]
> Tyyyyler, wrap up this PR!

wrapped! #49

**Comment by elizabethshirley** [comment]
👏👏👏👏 yaaaassssss

Real talk, but I know (from dealing with enough juniors) you won't listen
until you go through your first regression:

You want logically short Pull-requests - like a feature or bug fix. When
you have a regression, and you find the bug is in *this* PR, you won't feel
like you lost all of this hard work, when you need to revert the merge on
master.

When you fail to merge reasonably, submitters also need to constantly
update their PRs, to stay mergable, that makes their PR harder and harder
to read too.

The second point I was going to bring up was keep your git history clean,
with `git rebase`, and find bugs with `git bisect`, but you'll have to
discover those on your own ;)

**Pull request closed without merging**
